version: '3'

services:
  calcul-distance-service:
     build:
            context: ./calculDistanceService
     ports:
        - "8081:8081"
        

  bordeaux-vls-service:
   
    build: ./bordeauxVlsService
    ports:
      - "8080:8080"
    links:
      - calcul-distance-service
   

    

      