FROM openjdk:8-jdk-alpine

COPY ./calculDistanceService-0.0.1-SNAPSHOT.jar /calculDistanceService-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","calculDistanceService-0.0.1-SNAPSHOT.jar"]  
