FROM openjdk:8-jdk-alpine

COPY ./bordeauxVlsService-0.0.1-SNAPSHOT.jar /bordeauxVlsService-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","bordeauxVlsService-0.0.1-SNAPSHOT.jar"]  
